# This is development environment, for production see _compose.override_prod.yml
services:
  nexus:
    # Disable analytics https://help.sonatype.com/en/in-product-analytics-capability.html
    environment:
      - INSTALL4J_ADD_VM_PARAMS=${INSTALL4J_ADD_VM_PARAMS} -Dnexus.analytics.enabled=false -Dnexus.datastore.enabled=true 
          -Dnexus.sso.h2.tcpListenerEnabled=true -Dnexus.sso.h2.tcpListenerPort=2424 -Dnexus.h2.httpListenerEnabled=true -Dnexus.h2.httpListenerPort=2480
    # Disabling "Analyze Application" https://stackoverflow.com/a/41726259/19707292
    extra_hosts:
      - clm.sonatype.com:0.0.0.0
      - rhc.sonatype.com:0.0.0.0
      - rhc-pro.sonatype.com:0.0.0.0
    dns:
      - ${NETWORK_DNS_RESOLVER_1:-8.8.8.8}
      - ${NETWORK_DNS_RESOLVER_2:-4.4.4.4}
      - ${NETWORK_DNS_RESOLVER_3:-192.168.0.1}
    volumes:
      - ${NEXUS_ETC}/logback:/opt/sonatype/nexus/etc/logback:ro
      - ${NEXUS_ETC}/jetty/nexus-web.xml:/opt/sonatype/nexus/etc/jetty/nexus-web.xml:ro
      - ${NEXUS_ETC}/jetty/jetty-sso.xml:/opt/sonatype/nexus/etc/jetty/jetty-sso.xml:ro
      - ${NEXUS_ETC}/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties:ro
      - ./nexus-pac4j-plugin/src/main/config:/opt/sonatype/nexus/etc/sso/config:ro
      - ./nexus-pac4j-plugin/src/main/groovy:/opt/sonatype/nexus/etc/sso/script:ro
      - ${NEXUS_ETC}/h2db:/h2db:rw # H2DB console config
    ports:
      - ${NEXUS_HTTP_PORT:-8081}:8081 # Nexus: http://localhost:8081/ (remove it from production environment)
      - ${DBCONSOLE_TCP_PORT:-2424}:2424 # H2DB: tcp://localhost:2424 (remove it from production environment)
      - ${DBCONSOLE_HTTP_PORT:-2481}:2480 # H2DB: http://localhost:2481 (remove it from production environment)