version: "3.9"

# See docs/Docker.md, change these settings for your production environment, ex.:
services:
  nexus:
    volumes:
      # All file volumes from compose.yml are inherited here, the following are added to them
      - ${NEXUS_ETC}/sso/config/shiro.ini:/opt/sonatype/nexus/etc/sso/config/shiro.ini:ro
      - ${NEXUS_ETC}/sso/config/metadata.xml:/opt/sonatype/nexus/etc/sso/config/metadata.xml:ro
      - ${NEXUS_ETC}/sso/config/sp-metadata.xml:/opt/sonatype/nexus/etc/sso/config/sp-metadata.xml:ro
    env_file:
      - .env_prod

  nginx:
    env_file:
      - .env_prod