version: "3.9"

# This is development environment, for production see _compose.override_prod.yml
services:
  nexus:
    dns:
      - ${NETWORK_DNS_RESOLVER_1:-8.8.8.8}
      - ${NETWORK_DNS_RESOLVER_2:-4.4.4.4}
      - ${NETWORK_DNS_RESOLVER_3:-192.168.0.1}
    volumes:
      - ${NEXUS_ETC}/logback:/opt/sonatype/nexus/etc/logback:ro
      - ${NEXUS_ETC}/jetty/nexus-web.xml:/opt/sonatype/nexus/etc/jetty/nexus-web.xml:ro
      - ${NEXUS_ETC}/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties:ro
      - ./nexus-bootstrap/src/main/config:/opt/sonatype/nexus/etc/sso/config:ro
      - ./nexus-bootstrap/src/main/static:/opt/sonatype/nexus/etc/sso/static:ro
      - ./nexus-bootstrap/src/main/groovy:/opt/sonatype/nexus/etc/sso/script:ro
    ports:
      - "${NEXUS_HTTP_PORT:-8081}:8081" # Nexus: http://localhost:8081/ (remove it from production environment)
      - "${ORIENTDB_BINARY_PORT:-2424}:2424" # OrientDB: tcp://localhost:2424 (remove it from production environment)
