version: "3.9"

# This is development environment, for production see _compose.override_prod.yml
services:
  nexus:
    # Disable analytics https://help.sonatype.com/en/in-product-analytics-capability.html
    environment:
      - "INSTALL4J_ADD_VM_PARAMS=${INSTALL4J_ADD_VM_PARAMS} -Dnexus.analytics.enabled=false"
    # Disabling "Analyze Application" https://stackoverflow.com/a/41726259/19707292
    extra_hosts:
      - clm.sonatype.com:0.0.0.0
      - rhc.sonatype.com:0.0.0.0
      - rhc-pro.sonatype.com:0.0.0.0
    dns:
      - ${NETWORK_DNS_RESOLVER_1:-8.8.8.8}
      - ${NETWORK_DNS_RESOLVER_2:-4.4.4.4}
      - ${NETWORK_DNS_RESOLVER_3:-192.168.0.1}
    volumes:
      - ${NEXUS_ETC}/logback:/opt/sonatype/nexus/etc/logback:ro
      - ${NEXUS_ETC}/jetty/nexus-web.xml:/opt/sonatype/nexus/etc/jetty/nexus-web.xml:ro
      - ${NEXUS_ETC}/jetty/jetty-sso.xml:/opt/sonatype/nexus/etc/jetty/jetty-sso.xml:ro
      - ${NEXUS_ETC}/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties:ro
      - ./nexus-pac4j-plugin/src/main/config:/opt/sonatype/nexus/etc/sso/config:ro
      - ./nexus-pac4j-plugin/src/main/groovy:/opt/sonatype/nexus/etc/sso/script:ro
    ports:
      - "${NEXUS_HTTP_PORT:-8081}:8081" # Nexus: http://localhost:8081/ (remove it from production environment)
      - "${ORIENTDB_BINARY_PORT:-2424}:2424" # OrientDB: tcp://localhost:2424 (remove it from production environment)
