version: "3.9"

x-container: &container
  restart: ${RESTART_POLICY:-unless-stopped}
  env_file:
    - .env

x-logging: &logging
  driver: "json-file"
  options:
    max-size: ${LOGGING_MAX_SIZE:-5M}
    max-file: ${LOGGING_COUNT_FILES:-10}

# docker compose up -d --wait --wait-timeout 45
services:
  # docker compose exec -- nexus curl -k http://localhost:8081/rewrite-status
  nexus:
    <<: *container
    image: ${NEXUS_IMAGE}
    user: ${NEXUS_USER:-nexus}:${NEXUS_GROUP:-nexus}
    cpus: ${NEXUS_CPUS:-4}
    mem_limit: ${NEXUS_MEM_LIMIT:-3000m}
    mem_reservation: ${NEXUS_MEM_RESERVATION:-512m}
    volumes:
      - ${NEXUS_DATA}:/nexus-data
    logging:
      <<: *logging
    healthcheck:
      test: curl --fail http://localhost:8081/service/rest/v1/status || exit 1
      start_period: ${HEAL_START_PERIOD:-60s}
      interval: ${HEAL_INTERVAL:-30s}
      timeout: ${HEAL_TIMEOUT:-2s}
      retries: ${HEAL_RETRIES:-5}

  # docker compose exec -- nginx nginx -s reload;
  nginx:
    <<: *container
    image: ${NGINX_IMAGE:-nginx:1.23.3}
    user: ${NGINX_USER:-0}:${NGINX_GROUP:-0}
    cpus: ${NGINX_CPUS:-2}
    mem_limit: ${NGINX_MEM_LIMIT:-256m}
    mem_reservation: ${NGINX_MEM_RESERVATION:-64m}
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    depends_on:
      nexus:
        condition: service_healthy
    volumes:
      - ${NEXUS_ETC:-./etc}/nginx:/etc/nginx/:ro
    logging:
      <<: *logging

  # docker compose --profile debug up
  # docker compose --profile debug up -d orientdb
  # docker compose --profile debug rm -sf orientdb
  orientdb:
    <<: *container
    image: ${ORIENTDB_IMAGE:-orientdb:2.2.37}
    cpus: ${ORIENTDB_CPUS:-2}
    mem_limit: ${ORIENTDB_MEM_LIMIT:-512m}
    mem_reservation: ${ORIENTDB_MEM_RESERVATION:-64m}
    volumes:
      - ${NEXUS_ETC}/orientdb:/orientdb/config:rw
    ports:
      - "${ORIENTDB_HTTP_PORT:-2480}:2480" # OrientDB: http://localhost:2480/studio/index.html
    depends_on:
      nexus:
        condition: service_healthy
    profiles:
      - debug
    logging:
      <<: *logging

networks:
  default:
    driver: ${NETWORK_DRIVER:-bridge}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.30.0.0/16}
